# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91bdd8567178e913fa68e13d7fbfb9d97879318924ea826b5495470838094c614122845890b2ccb409c99108a3bdab8a07b3d591d43c1d3db4e59b402e14c035

test:
  secret_key_base: cfbd791cfbb0228f5b0778c339969fcc2493858ccf9003054154122d9931201bfd5d77fcd7e82eb1a2d4599e13435e1b189e84c2965ee9a51072b98bab505680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
